sudo: required
language: generic
services: 
    - docker

before_install:
    - docker build -t 926110576269.dkr.ecr.us-east-1.amazonaws.com/helloworld:1.1 .
    - docker push 926110576269.dkr.ecr.us-east-1.amazonaws.com/helloworld:1.1