sudo: required
language: generic
services:
- docker
env:
  global:
  - DOCKER_REPO=twohyjr/helloworld
  - EB_REGION="us-east-1"
before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
script:
- docker build -t $DOCKER_REPO .
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master