sudo: required
language: generic
services: 
    - docker

before_install:
    - docker build -t 926110576269.dkr.ecr.us-east-1.amazonaws.com/helloworld:latest .

    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin 926110576269.dkr.ecr.us-east-1.amazonaws.com

    - docker push 926110576269.dkr.ecr.us-east-1.amazonaws.com/helloworld:latest