sudo: required
language: generic
services: 
    - docker

before_install:
    - docker build -t twohyjr/docker-helloworld .
    #Log into the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
    #Push images to docker hub
    - docker push twohyjr/docker-helloworld 

# deploy:
#     provider: elasticbeanstalk
#     region: "us-east-1"
#     app: docker-helloworld
#     env: "DockerHelloworld-env"
#     bucket_name: "elasticbeanstalk-us-east-1-926110576269"
#     bucker_path: "docker-helloworld" #the app name
#     on:
#         branch: master #when we push to master DEPLOY!
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY
    